"""
Neural Observatory — HTML Reporter
"""
from __future__ import annotations

import datetime
import html
from pathlib import Path
from typing import List, Optional, Union

from .base import BaseReporter, Report
from ..analysis.base import AnalysisResult, AnalysisStatus
from ..core.configuration import ObservatoryConfig


_STATUS_COLORS = {
    AnalysisStatus.HEALTHY:  ("#d4edda", "#155724"),
    AnalysisStatus.INFO:     ("#d1ecf1", "#0c5460"),
    AnalysisStatus.WARNING:  ("#fff3cd", "#856404"),
    AnalysisStatus.CRITICAL: ("#f8d7da", "#721c24"),
}

# Inline CSS so the generated report is a single, portable standalone file.
_CSS = """
* { box-sizing: border-box; margin: 0; padding: 0; }
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
       background: #f8f9fa; color: #212529; padding: 2rem; }
h1 { font-size: 1.8rem; font-weight: 700; margin-bottom: 0.25rem; }
.subtitle { color: #6c757d; margin-bottom: 2rem; font-size: 0.9rem; }
.summary-card {
  background: white; border-radius: 8px; padding: 1.5rem;
  box-shadow: 0 1px 3px rgba(0,0,0,.1); margin-bottom: 2rem;
  display: flex; gap: 2rem; flex-wrap: wrap; align-items: center;
}
.summary-item { text-align: center; }
.summary-item .value { font-size: 2rem; font-weight: 700; }
.summary-item .label { font-size: 0.75rem; color: #6c757d; text-transform: uppercase; }
.section { background: white; border-radius: 8px; box-shadow: 0 1px 3px rgba(0,0,0,.1);
           margin-bottom: 1.5rem; overflow: hidden; }
.section-header { padding: 1rem 1.5rem; background: #f8f9fa;
                  border-bottom: 1px solid #dee2e6; font-weight: 600; font-size: 1rem; }
table { width: 100%; border-collapse: collapse; }
th { background: #f8f9fa; padding: 0.6rem 1rem; text-align: left;
     font-size: 0.75rem; text-transform: uppercase; letter-spacing: .05em;
     color: #6c757d; border-bottom: 1px solid #dee2e6; }
td { padding: 0.75rem 1rem; border-bottom: 1px solid #f0f0f0;
     font-size: 0.875rem; vertical-align: top; }
tr:last-child td { border-bottom: none; }
.badge { display: inline-block; padding: 0.25em 0.6em; border-radius: 4px;
         font-size: 0.75rem; font-weight: 600; letter-spacing: .04em; }
.warnings { margin-top: 0.4rem; }
.warning-item { font-size: 0.8rem; color: #856404; }
.metric { color: #495057; }
.metric-key { color: #6c757d; font-size: 0.75rem; }
footer { margin-top: 3rem; color: #adb5bd; font-size: 0.8rem; text-align: center; }
"""


class HTMLReporter(BaseReporter):
    def __init__(self, output_path: Union[str, Path, None] = None) -> None:
        self._path = Path(output_path or "observatory_report.html")

    def report(
        self,
        report: Report,
        config: Optional[ObservatoryConfig] = None,
    ) -> None:
        cfg = config or ObservatoryConfig()
        html_str = self._render(report, cfg)
        self._path.write_text(html_str, encoding="utf-8")
        print(f"[HTMLReporter] Report written to {self._path.resolve()}")

    def _render(self, report: Report, cfg: ObservatoryConfig) -> str:
        results = report.filtered(
            min_severity=cfg.report_min_severity,
            max_results=cfg.report_max_layers,
            include_healthy=cfg.report_include_healthy,
        )

        summary = report.summary_dict()
        ts = datetime.datetime.fromtimestamp(report.timestamp).strftime(
            "%Y-%m-%d %H:%M:%S"
        )

        body_parts = [
            self._summary_card(summary, ts),
        ]

        by_analyzer: dict = {}
        for r in results:
            by_analyzer.setdefault(r.analyzer_name, []).append(r)

        for name, res in sorted(by_analyzer.items()):
            body_parts.append(self._section(name, res))

        body = "\n".join(body_parts)
        footer = f'<footer>Generated by Neural Observatory · {ts}</footer>'

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Neural Observatory Report — Step {report.step}</title>
  <style>{_CSS}</style>
</head>
<body>
  <h1>🔭 Neural Observatory</h1>
  <p class="subtitle">
    Step {report.step} &nbsp;·&nbsp; Epoch {report.epoch} &nbsp;·&nbsp; {ts}
  </p>
  {body}
  {footer}
</body>
</html>"""

    def _summary_card(self, summary: dict, ts: str) -> str:
        status = summary["overall_status"]
        severity = summary["max_severity"]
        sc = summary["status_counts"]
        overall_status = AnalysisStatus(status)
        _, fg = _STATUS_COLORS.get(overall_status, ("#f8f9fa", "#333"))

        return f"""
<div class="summary-card">
  <div class="summary-item">
    <div class="value" style="color:{fg}">{status.upper()}</div>
    <div class="label">Overall Status</div>
  </div>
  <div class="summary-item">
    <div class="value" style="color:#dc3545">{sc.get('critical', 0)}</div>
    <div class="label">Critical</div>
  </div>
  <div class="summary-item">
    <div class="value" style="color:#ffc107">{sc.get('warning', 0)}</div>
    <div class="label">Warnings</div>
  </div>
  <div class="summary-item">
    <div class="value" style="color:#28a745">{sc.get('healthy', 0)}</div>
    <div class="label">Healthy</div>
  </div>
  <div class="summary-item">
    <div class="value">{severity:.2f}</div>
    <div class="label">Max Severity</div>
  </div>
</div>"""

    def _section(self, analyzer_name: str, results: List[AnalysisResult]) -> str:
        title = analyzer_name.upper().replace("_", " ")
        rows = "\n".join(self._row(r) for r in results)
        return f"""
<div class="section">
  <div class="section-header">{html.escape(title)}</div>
  <table>
    <thead>
      <tr>
        <th>Layer</th>
        <th>Status</th>
        <th>Severity</th>
        <th>Key Metrics</th>
        <th>Notes</th>
      </tr>
    </thead>
    <tbody>{rows}</tbody>
  </table>
</div>"""

    def _row(self, r: AnalysisResult) -> str:
        bg, fg = _STATUS_COLORS.get(r.status, ("#f8f9fa", "#333"))
        badge = (
            f'<span class="badge" style="background:{bg};color:{fg}">'
            f'{r.status.value.upper()}</span>'
        )

        metrics_html = self._metrics_html(r.metrics)

        warnings_html = ""
        if r.warnings:
            items = "".join(
                f'<div class="warning-item">⚠ {html.escape(w)}</div>'
                for w in r.warnings
            )
            warnings_html = f'<div class="warnings">{items}</div>'

        return f"""<tr>
  <td><code>{html.escape(r.layer_name)}</code></td>
  <td>{badge}</td>
  <td>{r.severity:.3f}</td>
  <td class="metric">{metrics_html}</td>
  <td>{warnings_html}</td>
</tr>"""

    @staticmethod
    def _metrics_html(metrics: dict) -> str:
        key_metrics = {
            k: v for k, v in metrics.items()
            if k not in ("num_observations", "has_nan", "has_inf",
                         "total_anomalies", "numel")
        }
        parts = []
        for k, v in list(key_metrics.items())[:3]:
            if isinstance(v, float):
                parts.append(f'<span class="metric-key">{html.escape(k)}=</span>'
                             f'<span>{v:.4f}</span>')
            else:
                parts.append(f'<span class="metric-key">{html.escape(k)}=</span>'
                             f'<span>{v}</span>')
        return " &nbsp; ".join(parts)